# -*- coding: utf-8 -*-
"""TEST MODEL

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bFtfjZhlG-Mb-pKZdtocwlzqq06C0YQx
"""

# Commented out IPython magic to ensure Python compatibility.
# %tensorflow_version 2.x
from tensorflow.keras.models import load_model
import requests
import numpy as np
import cv2
import matplotlib.pyplot as plt
import json

bin_ages_=[  1.,   2.,   4.,   8.,  13.,  17.,  21.,  24.,  25.,  26.,  28.,
        29.,  31.,  34.,  36.,  38.,  42.,  47.,  51.,  55.,  60.,  66.,
        76., 116.,120]

face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades+'haarcascade_frontalface_alt2.xml')

model = load_model("Save_models/model_v2.model")


"""TEST THE MODEL USING URL LINKS"""

img = cv2.imread('/test_img/faces.png')
img = cv2.resize(img,(300,300))
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
a =-5
faces = face_cascade.detectMultiScale(gray, 1.1, 5)

for (x,y,w,h) in faces:
      cv2_imshow(img[y:y+h+25,x+5:x+w-10])
      img_ = img[y-a:y+h+a+10,x-a:x+w+a]
      img_ = cv2.resize(img_,(100,100))
      i = np.argmax(model.predict(img_.reshape(1,100,100,3)/255.0)[0])
      print('age: ',bin_ages_[i],'-',bin_ages_[i+1])